baseURL = "https://harishbommakanti.github.io"
title = "Harish Bommakanti"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
publishdir = "./docs/"
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Harish Bommakanti"
description = "Harish Bommakanti's personal website"
keywords = "blog,developer,personal"
info = ["CS Senior @ UT Austin","Looking for 2023 Full Time Software Roles"]
avatarURL = "images/avatar.jpg"
#gravatar = "harish.bommakanti@utexas.edu"
favicon_32 = "images/favicon.png"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
#commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'", 
  "'unsafe-inline'", 
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 1
url = "mailto:harish.bommakanti@utexas.edu"

[[params.social]]
name = "GitHub"
icon = "fa fa-2x fa-github"
weight = 2
url = "https://github.com/harishbommakanti/"

#[[params.social]]
#name = "GitLab"
#icon = "fa fa-2x fa-gitlab"
#weight = 2
#url = "https://gitlab.com/johndoe/"

#[[params.social]]
#name = "Twitter"
#icon = "fa fa-2x fa-twitter"
#weight = 3
#url = "https://twitter.com/johndoe/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/harishbommakanti/"

[[params.social]]
name = "Resume"
icon = "fa fa-2x fa-file"
weight = 5
url = "files/HarishBommakantiResume.pdf"

#[[params.social]]
#name = "Medium"
#icon = "fa fa-2x fa-medium"
#weight = 5
#url = "https://medium.com/@johndoe"

#[[params.social]]
#name = "RSS"
#icon = "fa fa-2x fa-rss"
#weight = 6
#url = "https://myhugosite.com/index.xml"
#rel = "alternate"
#type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Skills"
weight = 2
url = "skills/"

[[languages.en.menu.main]]
name = "Education"
weight = 3
url = "education/"

[[languages.en.menu.main]]
name = "Experience"
weight = 4
url = "experience/"

[[languages.en.menu.main]]
name = "Projects"
weight = 5
url = "projects/"
