baseURL: "https://harishbommakanti.github.io"
languageCode: "en-us"
title: "Harish Bommakanti"
theme: hugo-profile

Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name:
      title: Blog posts
      url: /blogs
      weight: 1
    
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Harish Bommakanti"
  description: Harish Bommakanti's Profile Website
  # staticPath: "/static"  # The path to serve the static files from
  favicon: "/images/favicon.jpg"

  # theme:
  #   disableThemeToggle: false
  #   defaultTheme: "dark" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

    # menus:
    #   disableAbout: false
    #   disableExperience: false
    #   disableEducation: false
    #   disableProjects: false
    #   disableAchievements: true
    #   disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Harish Bommakanti"
    subtitle: "CS Junior @ UT Austin"
    content: "Passionate about Software Development, AI, and efficient problem solving in general. Seeking internship roles for Summer 2023."
    image: "images/face.jpg"
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/harishbommakanti
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/harishbommakanti
        - icon: fa fa-envelope
          url: mailto:harish.bommakanti@utexas.edu
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    # image: "/images/face.jpg"
    content: |-
      I am a junior pursuing a BS CS at UT Austin, planning to graduate in Winter 2023.
      I have experience working at university research labs, Mythic Inc, and Samsung in areas spanning from firmware to AI.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Java"
        - "C"
        - "C++"
        - "Git/GitHub/GitLab/Gerrit"
        - "Atlassian Suite"
        - "Scikit-Learn"
        - "PyTorch"

  # Experience
  experience:
    enable: true
    items:
      - job: "GPU Software Intern"
        company: "Samsung Electronics"
        companyUrl: "https://www.samsung.com/us/"
        date: "May 2022 - Jul 2022"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
          content: I
        content: |-
          - c++ and cmake for bpmd dumps
      
      - job: "Firmware Engineer Intern"
        company: "Mythic"
        companyUrl: "https://mythic-ai.com"
        date: "May 2021 - Aug 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          - Integrated new features/bug fixes to the customer facing Python API and firmware facing C API, resulting in a more serviceable AI accelerator chip.
          - Collaborated with other software and hardware teams frequently to resolve product specification issues.
          - Operated under the Agile Scrum methodology and completed 250% of the work assigned for the term.

      - job: "Undergraduate Teaching Assistant"
        company: "UT Austin"
        companyUrl: "https://www.cs.utexas.edu/"
        date: "Jan 2021 - May 2021"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Guided learning in lecture and office hours for ~200 students in Introduction to Python as a Teaching Assistant.
          - Wrote automated grading software in Python to grade student homework submissions.
      - job: "Volunteer Research Assistant"
        company: "UT Austin Research Labs"
        companyUrl: "https://research.utexas.edu/"
        date: "Jun 2019 - Present"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
        content: |-
          - Jan 2022 - May 2022: Contributed visualization tools and added tracking of most significant timesteps in active classification, an AI model which aims to classify agents as malicious or not based on their actions in an environment.
          - Oct 2020 - Jun 2021: Tuned the PPO reinforcement learning algorithm in Python to demonstrate the usability of Robosuite, a robotics simulation framework.
          - Jun 2019: Ran simulations on TACC supercomputers using software developed by the CHG labs to simulate coastal models.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "University of Texas at Austin"
          url: "https://utexas.edu"
        date: "2020 - 2023"
        GPA: "3.81 out of 4.0"
        content: |-
          Computer Science Coursework:
            - Safe and Ethical AI, AI, Algorithms, Programming for Correctness and Performance, Operating Systems, Computer Architecture, Robot Learning, Data Structures

          Mathematics Coursework:
            - Linear Algebra, Introduction to Probability and Statistics, Multivariate Calculus
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "Rouse High School"
        # school:
        #   # name: "Rouse"
        #   url: "https://rhs.leanderisd.org/"
        date: "2016 - 2020"
        GPA: "4.0 out of 4.0"
        content: |-
          Programs
            - NASA SEES
              - Aggregated precipitation data for 100s of Texas locations through National Weather Service REST endpoints with JavaScript to host on a Center for Space Research website.
            - NASA HAS
              - Selected as 1 of 500 high school juniors to complete a yearlong NASA certified online course, and 1 of 270 to visit the Johnson Space Center and receive exclusive tours of JSC facilities.

          Extracurriculars:
            - FRC Robotics:
              - Software Lead. Won awards such as Rookie All Star and Creativity Awards. Reached World Championships multiple times.
            - UIL Mathematics/Computer Science
              - Placed in the top 15 at district events many times.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Algorithms Class Projects
        content: Experimented and implemented classic algorithms from dynamic programming, graphs, search, network flow, linear programming, and complexity theory.
        image: "images/projects/ut.png"
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "Python"
          - "Jupyter Notebook"
        # links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          # - icon: fab fa-github
          #   url: https://github.com/gurusabarish/hugo-profile
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
      - title: Operating System Class Projects
        content: Built a shell application to process command-line Linux arguments and launch/coordinate process communication in C. Added features to threading, system call, virtual memory, and file storage systems to the Pintos operating system.
        image: "images/projects/ut.png"
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "C"
        # links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          # - icon: fab fa-github
          #   url: https://github.com/gurusabarish/hugo-profile
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Computer Architecture Class Projects
        content: Build a command line interpreter for a subset of the EEL language. Developed a dynamic memory manager to emulate malloc and free. Designed a simulator in C capable of executing Y86-64 Assembly.
        image: "images/projects/ut.png"
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "C"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      - title: Weather Prediction
        content: A CLI program in Python to predict weather data using time series modeling.
        image: "images/projects/weather-prediction.png"
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Python"
          - "ML/AI"
        links:
          - icon: fab fa-github
            url: https://github.com/harishbommakanti/weather-prediction
    
      - title: Robotics Scouting App
        content: Authored a web application to automate data gathering at high school robotics events.
        image: "images/projects/scouting_app.png"
        featured:
          name: Website
          link: https://scouting.rouserobotics.com/
        badges:
          - "JavaScript"
          - "HTML/CSS"
          - "Jekyll"
        links:
          - icon: fab fa-github
            url: https://github.com/Team6321/Scouting_App

  #Contact
  contact:
    enable: true
    content: Feel free to reach out if you or anyone you know may be interested in working with me!
    email: harish.bommakanti@utexas.edu
    btnName: Email

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/harishbommakanti
      linkedin: https://linkedin.com/in/harishbommakanti