name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy to vuepress
      uses: grasilife/github-pages-deploy-action@v1.2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: build
        BRANCH: master
        FOLDER: .vuepress/dist
        BUILD_SCRIPT: npm install && npm run docs:build