name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vuepress deploy
      uses: jenkey2011/vuepress-deploy@1.0.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: harishbommakanti/harishbommakanti.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm install -g vuepress && vuepress build ./
        BUILD_DIR: .vuepress/dist